
# Cadastrar usuário
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "email": "teste@gmail.com",
  "username": "teste",
  "password": "123"
}

###


# Buscar usuário ( Inserir o ID correto )
GET http://localhost:8080/api/user/3

###


# Listar usuários
GET http://localhost:8080/api/user

###

# Atualizar usuário ( Inserir o ID correto )
PUT http://localhost:8080/api/user/3
Content-Type: application/json

{
  "email": "test@gmail.com",
  "username": "test",
  "password": "123456"
}


###

# Deletar usuário ( Inserir o ID correto )
DELETE http://localhost:8080/api/user/4