

# Buscar preferência por ID do User ( Inserir o ID correto ) - Necessário usuário estar logado!*
GET http://localhost:8080/api/preferences/user/5


###

###

# Atualizar preferência por ID ( Inserir o ID correto ) - Necessário usuário estar logado!*
PUT http://localhost:8080/api/preferences/5
Content-Type: application/json

{
  "theme": "light",
  "color_scheme": "light-grey",
  "categories": "stared",
  "labels": "grey"
}


###

# Deletar preferência ( Inserir o ID correto ) - Necessário usuário estar logado!*
DELETE http://localhost:8080/api/preferences/5