

# Cadastrar preferências - Necessário usuário estar logado!*
POST http://localhost:8080/api/preferences
Content-Type: application/json

{
  "theme": "dark",
  "colorScheme": "dark-purple",
  "categories": "stared",
  "labels": "purple",
  "userId": 11
}

###


# Buscar preferência ( Inserir o ID correto ) - Necessário usuário estar logado!*
GET http://localhost:8080/api/preferences/5


###


# Listar preferências de um usuário ( Inserir o ID correto ) - Necessário usuário estar logado!*
GET http://localhost:8080/api/preferences/user/11


###

# Atualizar preferência ( Inserir o ID correto ) - Necessário usuário estar logado!*
PUT http://localhost:8080/api/preferences/5
Content-Type: application/json

{
  "theme": "light",
  "color_scheme": "light-grey",
  "categories": "stared",
  "labels": "grey",
  "user_id": 3
}


###

# Deletar preferência ( Inserir o ID correto ) - Necessário usuário estar logado!*
DELETE http://localhost:8080/api/preferences/5