version: '3.8'

services:
  locaweb:
      image: locaweb-api:latest
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        - POSTGRES_DB_URL=
