version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-database-locaweb
    environment:
      MYSQL_ROOT_PASSWORD: locaweb123
      MYSQL_DATABASE: locaweb
      MYSQL_USER: locaweb
      MYSQL_PASSWORD: locaweb123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: