

# Enviar email
POST http://localhost:8080/api/email
Content-Type: application/json

{
  "sentByUser": "user1@gmail.com",
  "receivedByUser": "user2@gmail.com",
  "subject": "Email Teste",
  "body": "Estou mandando um email teste"
}

###

# Buscar Email por ID ( Com Body )
GET http://localhost:8080/api/email/9

###

# Listar emails enviados pelo usuário ( Sem Body )
GET http://localhost:8080/api/email/sent/10

###

# Listar emails recebidos do usuário ( Sem Body )
GET http://localhost:8080/api/received/received/10

###

# Deletar Email por ID
DELETE http://localhost:8080/api/email/1

###